language: node_js
sudo: false

os:
  - linux
  - osx

node_js:
  - '7.0.0'
  - '7.1.0'
  - '7.2.0'
  - '7.3.0'
  - '7.4.0'
  - '7.5.0'
  - '7.6.0'
  - '7.7.2'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test
